services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: goworkforce
      MYSQL_USER: goworkforce_user
      MYSQL_PASSWORD: goworkforce_password
    ports:
      - "3306:3306"
    networks:
      - goworkforce-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: goworkforce_user
      DB_PASSWORD: goworkforce_password
      DB_NAME: goworkforce
      JWT_SECRET: your-secret-key-change-in-production
      PORT: 8080
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - goworkforce-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  goworkforce-network:
    driver: bridge

volumes:
  mysql_data: